### ISSUE TITLE
Update poetry.lock for starlette update after Dependabot patch

### ISSUE THREAD

**Issue by jcadam14** [cfpb/regtech-api-commons#14]
Dependabot updated Fastapi to 0.109.1.  The poetry.lock file didn't update starlette however to 0.36.3.

Push up updated poetry.lock to satisfy security issue.

**Comment by hkeeler** [comment]
We can close this now, yes?

**Comment by jcadam14** [comment]
Yup, closing due to #8 updating starlette.
